# Emulator generated coordinates
import math
from ref_input import reference_coordinate


def gps_emulator():  # GPS emulator - To generate coordinates within a set radius
    radial_distance = 0.004  # in km - radius for generating test coordinates
    centre_lat, centre_long = reference_coordinate()

    sample_points = 10000

    sample_coordinates = []
    for i in range(sample_points):
        angle = math.pi * 2 * i / sample_points
        dx = radial_distance * math.cos(angle)
        dy = radial_distance * math.sin(angle)
        point = ((centre_lat + (180 / math.pi) * (dy / 6371)),
                 (centre_long + (180 / math.pi) * (dx / 6371) / math.cos(centre_long * math.pi / 180)))
        sample_coordinates.append(point)
    return sample_coordinates


def emulated_coordinates():  # Sample set of data generated by emulator
    coordinates = gps_emulator()
    return coordinates
